version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  barbar-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - barbar-logs:/app/winston
      - ./uploads:/app/uploads
      - /app/node_modules
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped
    command: npm run dev

volumes:
  barbar-logs:
